name: Mirror LineageOS ROM

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download ROM
        run: |
          wget https://b4.timschumi.net/lineage-archive/lineage-20.0-20240208-nightly-Mi439-signed.zip

      - name: Verify file exists
        run: ls -lh .

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: lineage-mi439-20240208
          name: "LineageOS 20.0 | Mi439 | 20240208"
          files: "lineage-20.0-20240208-nightly-Mi439-signed.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
