name: Mirror Lineage ROM

on:
  workflow_dispatch:

jobs:
  download_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download ROM
        run: |
          FILE_NAME="lineage-20.0-20240201-nightly-Mi439-signed.zip"
          wget -c "https://b4.timschumi.net/lineage-archive/lineage-20.0-20240208-nightly-Mi439-signed.zip" -O "$FILE_NAME"

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "lineage-mi439-20240201"
          name: "LineageOS 20.0 20240201 Mi439"
          files: "$FILE_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
